export const EXTENSION_NAME = 'steambulksell';
export const CONTROLS_WRAPPER = '#inventory_logos';
export const APP_LOGO = '#inventory_applogo';
export const LOG_WRAPPER = '#inventory_logos';
export const INVENTORIES_WRAPPER = ':scope #active_inventory_page #inventories';
export const INVENTORY = '.inventory_ctn';
export const INVENTORY_PAGE = '.inventory_page';
export const ITEM_HOLDER = '.itemHolder';
export const PREVIOUS_INVENTORY_PAGE = '#pagebtn_previous';
export const NEXT_INVENTORY_PAGE = '#pagebtn_next';
export const INVENTORY_PAGE_TABS = ':scope .games_list_tabs .games_list_tab[id^="inventory_link_"]';
export const MODAL_WRAPPER = '#BG_bottom';
export const FILTER_OPTIONS = '#filter_options';
